name: Test Deploy

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Run Command
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}
        run: |
          docker compose up --build -d
